/* chains.js — GENERATED by scripts/gen-chains.mjs from .env.contracts. Do not edit.
 *
 * The deployed GraspLog targets (D-9: one primary, one or more mirrors),
 * in the shape the pages read straight off the chain. Generated rather than
 * hand-kept so a page cannot show an address the deploy scripts never
 * produced; `gen:chains` in CI fails if this drifts from its source.
 */
export const CHAINS = [
  {
    "id": 43113,
    "name": "Avalanche Fuji",
    "role": "primary",
    "rpc": "https://api.avax-test.network/ext/bc/C/rpc",
    "explorer": "https://testnet.snowtrace.io",
    "log": "0xDF1F8B068229C868be073eA4883186513AC059Fd",
    "verifier": "0x46bb2769C3F55A4Ae0cdA0885F14d191b5D1E307",
    "registry": "0xe4565B5Fd752A368DDbF90AB6ca4B321cb4df26D"
  }
];
