/* chains.js — GENERATED by scripts/gen-chains.mjs from .env.contracts.example. Do not edit.
 *
 * The deployed GraspLog targets (D-9: one primary, one or more mirrors),
 * in the shape the pages read straight off the chain. Generated rather than
 * hand-kept so a page cannot show an address the deploy scripts never
 * produced; `gen:chains` in CI fails if this drifts from its source.
 */
export const CHAINS = [
  {
    "id": 43113,
    "name": "Avalanche Fuji",
    "role": "primary",
    "rpc": "https://api.avax-test.network/ext/bc/C/rpc",
    "explorer": "https://testnet.snowtrace.io",
    "log": "0x0000000000000000000000000000000000000000",
    "verifier": "0x0000000000000000000000000000000000000000",
    "registry": "0x0000000000000000000000000000000000000000"
  },
  {
    "id": 11155111,
    "name": "Ethereum Sepolia",
    "role": "mirror",
    "rpc": "https://ethereum-sepolia-rpc.publicnode.com",
    "explorer": "https://sepolia.etherscan.io",
    "log": "0x0000000000000000000000000000000000000000",
    "verifier": "0x0000000000000000000000000000000000000000"
  }
];
