/* chains.js — GENERATED by scripts/gen-chains.mjs from .env.contracts. Do not edit.
 *
 * The deployed GraspLog targets (D-9: one primary, one or more mirrors),
 * in the shape the pages read straight off the chain. Generated rather than
 * hand-kept so a page cannot show an address the deploy scripts never
 * produced; `gen:chains` in CI fails if this drifts from its source.
 */
export const CHAINS = [
  {
    "id": 43113,
    "name": "Avalanche Fuji",
    "role": "primary",
    "rpc": "https://api.avax-test.network/ext/bc/C/rpc",
    "explorer": "https://testnet.snowtrace.io",
    "log": "0xde2E34b8A97774807842470b2619dC8BB099EaF1",
    "verifier": "0x44589a2464C4CD29df57CB757fC3e1296c38b565",
    "registry": "0x1a89aB71F65E50B36Eae138268Dc8D8f44f23Ccd"
  }
];
