/* embodiments.js — GENERATED by scripts/gen-embodiments.mjs. Do not edit.
 *
 * The browser copy of the registry. Generated rather than hand-kept so the
 * builder cannot offer a robot, a licence or a DoF count the exporter does not
 * have; `embodiments.test.mjs` fails if this drifts.
 */
export const EMBODIMENTS = [
  {
    "id": "unitree_g1",
    "name": "G1",
    "vendor": "Unitree",
    "class": "humanoid",
    "dof": 43,
    "licence": "BSD-3-Clause",
    "menagerie": "unitree_g1",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ],
    "note": "The volume humanoid: cheapest real hardware, widest community, most existing teleop data. Start here."
  },
  {
    "id": "unitree_h1",
    "name": "H1",
    "vendor": "Unitree",
    "class": "humanoid",
    "dof": 19,
    "licence": "BSD-3-Clause",
    "menagerie": "unitree_h1",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ],
    "note": "Full-size, high-power. Locomotion and loco-manipulation."
  },
  {
    "id": "apptronik_apollo",
    "name": "Apollo",
    "vendor": "Apptronik",
    "class": "humanoid",
    "dof": 30,
    "licence": "Apache-2.0",
    "menagerie": "apptronik_apollo",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ],
    "note": "Commercial warehouse humanoid. Credible for logistics tasks."
  },
  {
    "id": "booster_t1",
    "name": "T1",
    "vendor": "Booster Robotics",
    "class": "humanoid",
    "dof": 23,
    "licence": "Apache-2.0",
    "menagerie": "booster_t1",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ]
  },
  {
    "id": "fourier_n1",
    "name": "N1",
    "vendor": "Fourier",
    "class": "humanoid",
    "dof": 23,
    "licence": "Apache-2.0",
    "menagerie": "fourier_n1",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ]
  },
  {
    "id": "pal_talos",
    "name": "TALOS",
    "vendor": "PAL Robotics",
    "class": "humanoid",
    "dof": 32,
    "licence": "Apache-2.0",
    "menagerie": "pal_talos",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ],
    "note": "European research standard, torque-controlled."
  },
  {
    "id": "berkeley_humanoid",
    "name": "Berkeley Humanoid",
    "vendor": "UC Berkeley",
    "class": "humanoid",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "berkeley_humanoid",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "robotis_op3",
    "name": "OP3",
    "vendor": "Robotis",
    "class": "humanoid",
    "dof": 20,
    "licence": "Apache-2.0",
    "menagerie": "robotis_op3",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ]
  },
  {
    "id": "pnd_adam_lite",
    "name": "Adam Lite",
    "vendor": "PNDbotics",
    "class": "humanoid",
    "dof": 25,
    "licence": "MIT",
    "menagerie": "pndbotics_adam_lite",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ]
  },
  {
    "id": "toddlerbot_2xc",
    "name": "ToddlerBot 2XC",
    "vendor": "Stanford",
    "class": "humanoid",
    "dof": 30,
    "licence": "MIT",
    "menagerie": "toddlerbot_2xc",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ]
  },
  {
    "id": "toddlerbot_2xm",
    "name": "ToddlerBot 2XM",
    "vendor": "Stanford",
    "class": "humanoid",
    "dof": 30,
    "licence": "MIT",
    "menagerie": "toddlerbot_2xm",
    "actionSpaces": [
      "ee_pose_gripper",
      "whole_body_retarget"
    ]
  },
  {
    "id": "agility_cassie",
    "name": "Cassie",
    "vendor": "Agility Robotics",
    "class": "biped",
    "dof": 10,
    "licence": "MIT",
    "menagerie": "agility_cassie",
    "actionSpaces": [
      "base_velocity"
    ],
    "note": "Legs only. Locomotion benchmark, not manipulation."
  },
  {
    "id": "unitree_go2",
    "name": "Go2",
    "vendor": "Unitree",
    "class": "quadruped",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "unitree_go2",
    "actionSpaces": [
      "base_velocity"
    ],
    "note": "The volume quadruped."
  },
  {
    "id": "unitree_go1",
    "name": "Go1",
    "vendor": "Unitree",
    "class": "quadruped",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "unitree_go1",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "unitree_a1",
    "name": "A1",
    "vendor": "Unitree",
    "class": "quadruped",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "unitree_a1",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "anymal_b",
    "name": "ANYmal B",
    "vendor": "ANYbotics",
    "class": "quadruped",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "anybotics_anymal_b",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "anymal_c",
    "name": "ANYmal C",
    "vendor": "ANYbotics",
    "class": "quadruped",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "anybotics_anymal_c",
    "actionSpaces": [
      "base_velocity"
    ],
    "note": "Industrial inspection, real commercial deployments."
  },
  {
    "id": "bd_spot",
    "name": "Spot",
    "vendor": "Boston Dynamics",
    "class": "quadruped",
    "dof": 12,
    "licence": "BSD-3-Clause",
    "menagerie": "boston_dynamics_spot",
    "actionSpaces": [
      "base_velocity"
    ],
    "trademarkCheck": true,
    "note": "Highest brand recognition. Check trademark before commercial use."
  },
  {
    "id": "barkour_v0",
    "name": "Barkour v0",
    "vendor": "Google",
    "class": "quadruped",
    "dof": 12,
    "licence": "Apache-2.0",
    "menagerie": "google_barkour_v0",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "barkour_vb",
    "name": "Barkour vB",
    "vendor": "Google",
    "class": "quadruped",
    "dof": 12,
    "licence": "Apache-2.0",
    "menagerie": "google_barkour_vb",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "franka_panda",
    "name": "Panda",
    "vendor": "Franka Emika",
    "class": "arm",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "franka_emika_panda",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ],
    "note": "The research standard. Most published datasets use it."
  },
  {
    "id": "franka_fr3",
    "name": "FR3",
    "vendor": "Franka Robotics",
    "class": "arm",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "franka_fr3",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "ur5e",
    "name": "UR5e",
    "vendor": "Universal Robots",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "universal_robots_ur5e",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ],
    "trademarkCheck": true,
    "note": "The industrial standard, highest real install base."
  },
  {
    "id": "ur10e",
    "name": "UR10e",
    "vendor": "Universal Robots",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "universal_robots_ur10e",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ],
    "trademarkCheck": true
  },
  {
    "id": "kuka_iiwa14",
    "name": "LBR iiwa 14",
    "vendor": "KUKA",
    "class": "arm",
    "dof": 7,
    "licence": "BSD-3-Clause",
    "menagerie": "kuka_iiwa_14",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ],
    "trademarkCheck": true
  },
  {
    "id": "kinova_gen3",
    "name": "Gen3",
    "vendor": "Kinova",
    "class": "arm",
    "dof": 7,
    "licence": "BSD-3-Clause",
    "menagerie": "kinova_gen3",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "flexiv_rizon4",
    "name": "Rizon 4",
    "vendor": "Flexiv",
    "class": "arm",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "flexiv_rizon4",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ],
    "note": "Force-controlled — directly relevant to contact data."
  },
  {
    "id": "flexiv_rizon4s",
    "name": "Rizon 4S",
    "vendor": "Flexiv",
    "class": "arm",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "flexiv_rizon4s",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "xarm7",
    "name": "xArm7",
    "vendor": "UFACTORY",
    "class": "arm",
    "dof": 7,
    "licence": "BSD-3-Clause",
    "menagerie": "ufactory_xarm7",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "lite6",
    "name": "Lite 6",
    "vendor": "UFACTORY",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "ufactory_lite6",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "viperx300",
    "name": "ViperX 300 6DOF",
    "vendor": "Trossen",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "trossen_vx300s",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "widowx250",
    "name": "WidowX 250 6DOF",
    "vendor": "Trossen",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "trossen_wx250s",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "unitree_z1",
    "name": "Z1",
    "vendor": "Unitree",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "unitree_z1",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "arx_l5",
    "name": "L5",
    "vendor": "ARX",
    "class": "arm",
    "dof": 6,
    "licence": "BSD-3-Clause",
    "menagerie": "arx_l5",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "agilex_piper",
    "name": "PiPER",
    "vendor": "AgileX",
    "class": "arm",
    "dof": 6,
    "licence": "MIT",
    "menagerie": "agilex_piper",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "rethink_sawyer",
    "name": "Sawyer",
    "vendor": "Rethink Robotics",
    "class": "arm",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "rethink_robotics_sawyer",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "so_arm100",
    "name": "SO-ARM100",
    "vendor": "TheRobotStudio",
    "class": "arm",
    "dof": 5,
    "licence": "Apache-2.0",
    "menagerie": "trs_so_arm100",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ],
    "note": "Sub-$500. The LeRobot community default."
  },
  {
    "id": "low_cost_arm",
    "name": "Low-Cost Robot Arm",
    "vendor": "Community",
    "class": "arm",
    "dof": 5,
    "licence": "Apache-2.0",
    "menagerie": "low_cost_robot_arm",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "yam",
    "name": "YAM",
    "vendor": "I2RT",
    "class": "arm",
    "dof": 6,
    "licence": "MIT",
    "menagerie": "i2rt_yam",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "seeed_devarm",
    "name": "reBot DevArm",
    "vendor": "Seeed Studio",
    "class": "arm",
    "dof": 6,
    "licence": "MIT",
    "menagerie": "seeed_studio_devarm",
    "actionSpaces": [
      "ee_pose_gripper",
      "joint_position"
    ]
  },
  {
    "id": "aloha",
    "name": "ALOHA",
    "vendor": "Stanford / Trossen",
    "class": "bimanual",
    "dof": 14,
    "licence": "BSD-3-Clause",
    "menagerie": "aloha",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "The reference bimanual platform; most imitation-learning work targets it."
  },
  {
    "id": "shadow_hand",
    "name": "Hand E3M5",
    "vendor": "Shadow Robot",
    "class": "hand",
    "dof": 24,
    "licence": "Apache-2.0",
    "menagerie": "shadow_hand",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "The dexterity benchmark."
  },
  {
    "id": "shadow_dex_ee",
    "name": "DEX-EE",
    "vendor": "Shadow Robot",
    "class": "hand",
    "dof": 12,
    "licence": "Apache-2.0",
    "menagerie": "shadow_dexee",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "allegro_hand",
    "name": "Allegro Hand V3",
    "vendor": "Wonik",
    "class": "hand",
    "dof": 16,
    "licence": "BSD-2-Clause",
    "menagerie": "wonik_allegro",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "The most common research hand."
  },
  {
    "id": "leap_hand",
    "name": "Leap Hand",
    "vendor": "CMU",
    "class": "hand",
    "dof": 16,
    "licence": "MIT",
    "menagerie": "leap_hand",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "robotiq_2f85",
    "name": "2F-85",
    "vendor": "Robotiq",
    "class": "gripper",
    "dof": 1,
    "licence": "BSD-2-Clause",
    "menagerie": "robotiq_2f85",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "The industrial gripper."
  },
  {
    "id": "panda_gripper",
    "name": "Panda Gripper",
    "vendor": "Franka Emika",
    "class": "gripper",
    "dof": 1,
    "licence": "Apache-2.0",
    "menagerie": "franka_emika_panda",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "umi_gripper",
    "name": "UMI Gripper",
    "vendor": "Stanford",
    "class": "gripper",
    "dof": 1,
    "licence": "MIT",
    "menagerie": "umi_gripper",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "Handheld capture without a robot — the closest existing thing to the Band."
  },
  {
    "id": "sharpa_wave",
    "name": "Sharpa Wave",
    "vendor": "Sharpa",
    "class": "hand",
    "dof": 16,
    "licence": "Apache-2.0",
    "menagerie": "sharpa_wave",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "Tactile-focused."
  },
  {
    "id": "xarm7_gripper",
    "name": "xArm Gripper",
    "vendor": "UFACTORY",
    "class": "gripper",
    "dof": 1,
    "licence": "BSD-3-Clause",
    "menagerie": "ufactory_xarm7",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "stretch3",
    "name": "Stretch 3",
    "vendor": "Hello Robot",
    "class": "mobile_manipulator",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "hello_robot_stretch_3",
    "actionSpaces": [
      "ee_pose_gripper"
    ],
    "note": "Real household deployments."
  },
  {
    "id": "stretch2",
    "name": "Stretch 2",
    "vendor": "Hello Robot",
    "class": "mobile_manipulator",
    "dof": 7,
    "licence": "BSD-3-Clause-Clear",
    "menagerie": "hello_robot_stretch",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "pal_tiago",
    "name": "TIAGo",
    "vendor": "PAL Robotics",
    "class": "mobile_manipulator",
    "dof": 8,
    "licence": "Apache-2.0",
    "menagerie": "pal_tiago",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "pal_tiago_dual",
    "name": "TIAGo++",
    "vendor": "PAL Robotics",
    "class": "mobile_manipulator",
    "dof": 15,
    "licence": "Apache-2.0",
    "menagerie": "pal_tiago_dual",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "google_robot",
    "name": "Google Robot",
    "vendor": "Google",
    "class": "mobile_manipulator",
    "dof": 7,
    "licence": "Apache-2.0",
    "menagerie": "google_robot",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "tidybot",
    "name": "TidyBot",
    "vendor": "Stanford",
    "class": "mobile_manipulator",
    "dof": 7,
    "licence": "MIT",
    "menagerie": "stanford_tidybot",
    "actionSpaces": [
      "ee_pose_gripper"
    ]
  },
  {
    "id": "skydio_x2",
    "name": "X2",
    "vendor": "Skydio",
    "class": "drone",
    "dof": 4,
    "licence": "Apache-2.0",
    "menagerie": "skydio_x2",
    "actionSpaces": [
      "base_velocity"
    ]
  },
  {
    "id": "crazyflie2",
    "name": "Crazyflie 2",
    "vendor": "Bitcraze",
    "class": "drone",
    "dof": 4,
    "licence": "MIT",
    "menagerie": "bitcraze_crazyflie_2",
    "actionSpaces": [
      "base_velocity"
    ]
  }
];

export const byId = (id) => EMBODIMENTS.find((e) => e.id === id);
export const byClass = (c) => EMBODIMENTS.filter((e) => e.class === c);
