// SPDX-License-Identifier: MIT
// GENERATED by packages/protocol/test/vectors.ts — do not edit by hand.
// These are produced by the off-chain reference implementation, so a passing
// test means the Solidity and the TypeScript agree on every hash.
pragma solidity ^0.8.24;

library Vectors {
    bytes constant CLIP_PREIMAGE = hex"01ebc84cbd75ba5516bf45e7024a9e12bc3c5c880f73e3a5beca7ebba52b2867a7c973f01c30db151771eca5d5661d5262b8df81b0f801adc18cd689e95256cb4e097b1bfd048585d5000c967c83edf6c040e12e37584a93ee7af931b473ce2f2be0a963fc269dbfbc06a8ddf8f46dde77423a203f59ab3c4e6ab2c6f7de2cb304000000006a8374c0000000006a8374fc000010680000000b06";
    bytes32 constant CLIP_LEAF = 0xa638fd10596b436636218ac0a3b9f56fd9c109315275c166fd011ca3736e12cc;

    uint64 constant N = 11;
    bytes32 constant ROOT_N = 0x54e52db853d259bef52ba2362e8d6eafd9cd046f433210646a3fef62734a39be;
    uint64 constant INCLUSION_INDEX = 4;
    bytes32 constant INCLUSION_LEAF = 0x2ffcc95b6a5f487325f9ec0c4780cf11c0f3186a7b1bbb0e7c465e39c4148646;

    uint64 constant M = 7;
    bytes32 constant ROOT_M = 0xbed0c6c234c80b3aca2bb90699a2108e0d574a83c75b1af7017158000e831ff7;

    bytes32 constant SPARSE_ROOT = 0x43bb8421ba078f69815e2a725b6c6554c586f42318fdc87c603889e00f50e259;
    bytes32 constant KEY_REVOKED = 0x889d362a741a9aeb7b9590585a74391d21bd7ade714784bfef4e11bf14328277;
    bytes32 constant VALUE_REVOKED = 0x036d62b10ea2f8f0e65a6f6de0acc21bd78c8ca75484eae04586a17530b39beb;
    bytes32 constant KEY_LIVE = 0xaedcbf57886d8af4041ef4ba7460d664edc16b60d674938ab4b91a9544b1f99c;
    uint256 constant BITMAP_IN = 0;
    uint256 constant BITMAP_OUT = 14474011154664524427946373126085988481658748083205070504932198000989141204992;

    function inclusionProof() internal pure returns (bytes32[] memory p) {
        bytes32[4] memory a = [bytes32(0xdc8701308d2fb31bf986706e31e9b37617f0651f1de2c9708a8e5d23141262d4), bytes32(0xd2df46bed8e735e6e2c89d5af570cac1359b27785c06a3269b51f8e7a0701b56), bytes32(0xc7b0534978c19e3aba8a6cf8df0868e965c56aa33894ca9af3f0be6a5cd97a53), bytes32(0xf408cdf67a24f9ac7e42e9dd3b7c622f780e46582ef88fa830799cbdb18b334c)];
        p = new bytes32[](4);
        for (uint256 i; i < 4; ++i) p[i] = a[i];
    }

    function consistencyProof() internal pure returns (bytes32[] memory p) {
        bytes32[5] memory a = [bytes32(0xdbee7c1deb9b8ee88148df362f46e20f7043e32f5421ca2310eb1958c75eb8ba), bytes32(0xf7487361e7ae4062ecc6c3ef6d563558bf5b03f1904cfd22ce2247fea7cb3636), bytes32(0x6f8547cf2512c91947d47e73b8e2df26cb686e0d94e90d206b55ebdb189ea40f), bytes32(0xc7b0534978c19e3aba8a6cf8df0868e965c56aa33894ca9af3f0be6a5cd97a53), bytes32(0xf408cdf67a24f9ac7e42e9dd3b7c622f780e46582ef88fa830799cbdb18b334c)];
        p = new bytes32[](5);
        for (uint256 i; i < 5; ++i) p[i] = a[i];
    }

    function sparseIn() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](0);
    }

    function sparseOut() internal pure returns (bytes32[] memory p) {
        bytes32[1] memory a = [bytes32(0xe2a42a0de879f2cc1f1ec5789ece6705091c4e311cd89486c75cdc982f7ad65b)];
        p = new bytes32[](1);
        for (uint256 i; i < 1; ++i) p[i] = a[i];
    }
}
