// SPDX-License-Identifier: MIT
// GENERATED by packages/protocol/test/vectors.ts — do not edit by hand.
// These are produced by the off-chain reference implementation, so a passing
// test means the Solidity and the TypeScript agree on every hash.
pragma solidity ^0.8.24;

library Vectors {
    // ------------------------------------------------------- 0x01 ClipLeaf
    bytes constant CLIP_PREIMAGE = hex"01ebc84cbd75ba5516bf45e7024a9e12bc3c5c880f73e3a5beca7ebba52b2867a7c973f01c30db151771eca5d5661d5262b8df81b0f801adc18cd689e95256cb4e097b1bfd048585d5000c967c83edf6c040e12e37584a93ee7af931b473ce2f2be0a963fc269dbfbc06a8ddf8f46dde77423a203f59ab3c4e6ab2c6f7de2cb304000000006a8374c0000000006a8374fc000010680000000b06";
    bytes32 constant CLIP_LEAF = 0xa638fd10596b436636218ac0a3b9f56fd9c109315275c166fd011ca3736e12cc;

    // ---------------------------------------------------- 0x02 EpisodeLeaf
    // Derived from fixtures/manifest.json via manifestToEpisode (§10.12) at
    // the fixed submittedAt below (never taken from the manifest itself).
    uint64 constant EPISODE_SUBMITTED_AT = 1756900060;
    bytes32 constant MANIFEST_HASH = 0x386f3842cc4b56591b5790179643186d4e994f513780b78f65f210980ea66502;
    bytes constant EPISODE_PREIMAGE = hex"02db97d36c037fcca7e27ba8bdd9e4f808081a7a7ddc60c504453430ec6c031416386f3842cc4b56591b5790179643186d4e994f513780b78f65f210980ea66502444444444444444444444444444444444444444444444444444444444444444455555555555555555555555555555555555555555555555555555555555555557f66cb32abb88ff43c61bbf1a23bc17eda360901ea15fda913f0c7d46d2104020000000068b82aa00000000068b82adc000030700000000b030000000000000000010000";
    bytes32 constant EPISODE_LEAF = 0x640561c53ca4945a3a120a31c474246a66905141bb2619ea3c2256fbc7e763c4;

    // ----------------------------------------------- 0x03 CorpusManifestLeaf
    bytes constant CORPUS_PREIMAGE = hex"033a8f351f016361fed60d923e4ddd534a4cacd69a18ef3ebae4d9c53619631eaf16d83dbbb9e8d53bfd47ca6db0757a6895765af1e00d95fbda2198ff865f22dfe0a963fc269dbfbc06a8ddf8f46dde77423a203f59ab3c4e6ab2c6f7de2cb3042802332cb60232155bd013f89ac155008bf711db6a24ac9ab175d3b9aa6de1be0000000000000003000000006a837524";
    bytes32 constant CORPUS_LEAF = 0xb1d2bed8ac84dff26de9d042cd4c5277ff9f1c2fe68d97bb2df464dd51adb0f6;

    // ------------------------------------------- 0x04 VerificationClaimLeaf
    bytes constant CLAIM_PREIMAGE = hex"04bc1d4ec4b78a20162396ca39bdbb71ed49b1def695391ded62ebcc4dbe0b711735c37139eb500e770db096e8df0e905b103801ce450ed4db7033be7bcb84c0e8a796c55ea29f5dc24bd3d0b2b98135fbd69c93e4cb27425fc13c60ea7e98c6960cd5a744698351307de80be8212a8f88a3a8b3fa55f79bdc2639c2fb65d15fc300030102000000006a837588";
    bytes32 constant CLAIM_LEAF = 0x09a57959bf5d13c484e1af7dc617b7f302c9abce70656320e2ab9cd005ab4f51;

    // ------------------------------------------ §10.4 fileLeaf / payloadHash
    // Three committed fixture files, bytewise-sorted by path.
    string constant FILE0_PATH = "a.txt";
    bytes32 constant FILE0_HASH = 0x6525d7a80f6595c67c381a6aa363723f05535756ec2847efe0f63d49ad274c69;
    bytes32 constant FILE0_LEAF = 0x4e618b1f40c8d318f1d8999755a25992c256e7352c110c63dfeb6214bb876c0f;

    string constant FILE1_PATH = "b.bin";
    bytes32 constant FILE1_HASH = 0x0251cf13aa5b18f1cbda7cddbe85f3dc536fc93df590c2d20ca9b28af1ed2c39;
    bytes32 constant FILE1_LEAF = 0x6e7ca9ea936e77da7777000be20d939d93bdeefc7bd8716cbc84b99dc3a61f29;

    string constant FILE2_PATH = "sub/c.parquet";
    bytes32 constant FILE2_HASH = 0xd9be3690475fff2773920161b324eb7b39c3c1483df2687cab99d84d1d44c478;
    bytes32 constant FILE2_LEAF = 0xaf870472d5aea677a5e577e01b5419ccac1571ed730facb3a0233d2522c8e0c2;

    bytes32 constant PAYLOAD_HASH = 0x30d375fe7cc10a5df387d73103e3b052f8075f16a8a22b933e6a1cc5251cbe7d;

    // -------------------------------------------------------------- §10.1 CT
    uint64 constant N = 11;
    bytes32 constant ROOT_N = 0x54e52db853d259bef52ba2362e8d6eafd9cd046f433210646a3fef62734a39be;
    uint64 constant INCLUSION_INDEX = 4;
    bytes32 constant INCLUSION_LEAF = 0x2ffcc95b6a5f487325f9ec0c4780cf11c0f3186a7b1bbb0e7c465e39c4148646;

    uint64 constant M = 7;
    bytes32 constant ROOT_M = 0xbed0c6c234c80b3aca2bb90699a2108e0d574a83c75b1af7017158000e831ff7;

    // ------------------------------------------------------------ §10.2 SMT
    bytes32 constant SPARSE_ROOT = 0x43bb8421ba078f69815e2a725b6c6554c586f42318fdc87c603889e00f50e259;
    bytes32 constant KEY_REVOKED = 0x889d362a741a9aeb7b9590585a74391d21bd7ade714784bfef4e11bf14328277;
    bytes32 constant VALUE_REVOKED = 0x036d62b10ea2f8f0e65a6f6de0acc21bd78c8ca75484eae04586a17530b39beb;
    bytes32 constant KEY_LIVE = 0xaedcbf57886d8af4041ef4ba7460d664edc16b60d674938ab4b91a9544b1f99c;
    uint256 constant BITMAP_IN = 0;
    uint256 constant BITMAP_OUT = 14474011154664524427946373126085988481658748083205070504932198000989141204992;

    function inclusionProof() internal pure returns (bytes32[] memory p) {
        bytes32[4] memory a = [bytes32(0xdc8701308d2fb31bf986706e31e9b37617f0651f1de2c9708a8e5d23141262d4), bytes32(0xd2df46bed8e735e6e2c89d5af570cac1359b27785c06a3269b51f8e7a0701b56), bytes32(0xc7b0534978c19e3aba8a6cf8df0868e965c56aa33894ca9af3f0be6a5cd97a53), bytes32(0xf408cdf67a24f9ac7e42e9dd3b7c622f780e46582ef88fa830799cbdb18b334c)];
        p = new bytes32[](4);
        for (uint256 i; i < 4; ++i) p[i] = a[i];
    }

    function consistencyProof() internal pure returns (bytes32[] memory p) {
        bytes32[5] memory a = [bytes32(0xdbee7c1deb9b8ee88148df362f46e20f7043e32f5421ca2310eb1958c75eb8ba), bytes32(0xf7487361e7ae4062ecc6c3ef6d563558bf5b03f1904cfd22ce2247fea7cb3636), bytes32(0x6f8547cf2512c91947d47e73b8e2df26cb686e0d94e90d206b55ebdb189ea40f), bytes32(0xc7b0534978c19e3aba8a6cf8df0868e965c56aa33894ca9af3f0be6a5cd97a53), bytes32(0xf408cdf67a24f9ac7e42e9dd3b7c622f780e46582ef88fa830799cbdb18b334c)];
        p = new bytes32[](5);
        for (uint256 i; i < 5; ++i) p[i] = a[i];
    }

    function sparseIn() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](0);
    }

    function sparseOut() internal pure returns (bytes32[] memory p) {
        bytes32[1] memory a = [bytes32(0xe2a42a0de879f2cc1f1ec5789ece6705091c4e311cd89486c75cdc982f7ad65b)];
        p = new bytes32[](1);
        for (uint256 i; i < 1; ++i) p[i] = a[i];
    }
}
