/**
 * T-011 — LeRobot dataset reader tests. Plain boolean assertions through
 * tsx, no test framework (matches the rest of `services/api/test`).
 *
 * Fixtures (committed, generated by `scripts/fixtures/make-lerobot-fixture.ts`
 * -- a TS script, not the Python `lerobot` package TASK-011.md names; the
 * `lerobot` package could not be installed in this environment, see
 * TASKS/REPORTS.md):
 *  - `fixtures/lerobot-v3/` — v3.0 chunked layout, 3 episodes.
 *  - `fixtures/lerobot-v2/` — v2.1-style per_episode layout, 1 episode.
 */
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
// @ts-ignore
import { parquetWriteFile } from "hyparquet-writer";
import { readDataset, readEpisodeFrames, type EpisodeRef } from "../src/ingest/lerobot.ts";

let fails = 0;
const ok = (c: boolean, m: string, x = "") => { if (!c) fails++; console.log(`${c ? "  ok  " : " FAIL "} ${m}${x ? ` — ${x}` : ""}`); };

const here = dirname(fileURLToPath(import.meta.url));
const V3_DIR = join(here, "fixtures", "lerobot-v3");
const V2_DIR = join(here, "fixtures", "lerobot-v2");

// =========================================================================
// v3 chunked fixture
// =========================================================================
{
  const { info, infoJsonHash, episodes } = await readDataset(V3_DIR);

  ok((info as any).codebase_version === "v3.0", "v3 fixture: codebase_version v3.0");
  ok(/^0x[0-9a-f]{64}$/.test(infoJsonHash), "v3 fixture: infoJsonHash is a 32-byte hex hash");
  ok(episodes.length === 3, "v3 fixture: 3 episodes", String(episodes.length));

  const [e0, e1, e2] = episodes;
  ok(e0.episodeIndex === 0 && e1.episodeIndex === 1 && e2.episodeIndex === 2, "v3 fixture: episode_index 0,1,2 in order");
  ok(e0.layout === "chunked" && e1.layout === "chunked" && e2.layout === "chunked", "v3 fixture: layout chunked");
  ok(e0.frames === 6 && e1.frames === 5 && e2.frames === 7, "v3 fixture: frame counts 6,5,7", JSON.stringify([e0.frames, e1.frames, e2.frames]));
  ok(e0.rateHz === 30 && e1.rateHz === 30 && e2.rateHz === 30, "v3 fixture: rateHz 30");
  ok(e0.durationMs === Math.round((6 / 30) * 1000), "v3 fixture: durationMs derived from frames/rateHz");
  ok(e0.embodiment === "so_arm100", "v3 fixture: embodiment from robot_type");
  ok(e0.instruction === "fold the towel" && e2.instruction === "stack the cups", "v3 fixture: instruction from episode tasks");
  ok(e0.success === true, "v3 fixture: success true (any frame's next.success true)", String(e0.success));

  // range: [start, end) row indices within the shared data chunk
  ok(
    e0.range?.frames?.[0] === 0 && e0.range?.frames?.[1] === 6 &&
    e1.range?.frames?.[0] === 6 && e1.range?.frames?.[1] === 11 &&
    e2.range?.frames?.[0] === 11 && e2.range?.frames?.[1] === 18,
    "v3 fixture: range.frames = [start, end) per episode",
    JSON.stringify([e0.range, e1.range, e2.range]),
  );
  const cam = "observation.images.front";
  ok(
    e0.range?.video?.[cam]?.[0] === 0 && Math.abs((e0.range?.video?.[cam]?.[1] ?? -1) - 0.2) < 1e-9,
    "v3 fixture: range.video[camera] = [t0, t1] seconds",
    JSON.stringify(e0.range?.video),
  );

  // files: sorted by path bytes, data chunk + video chunk
  ok(e0.files.length === 2, "v3 fixture: files = data chunk + video chunk", String(e0.files.length));
  ok(
    e0.files[0].path === "data/chunk-000/file-000.parquet" &&
    e0.files[1].path === `videos/${cam}/chunk-000/file-000.mp4`,
    "v3 fixture: files sorted by path bytes",
    JSON.stringify(e0.files.map((f) => f.path)),
  );
  ok(e0.files.every((f) => /^0x[0-9a-f]{64}$/.test(f.hash) && f.bytes > 0), "v3 fixture: file hashes/bytes populated");
  // same data+video files are shared across all 3 episodes -> same hashes
  ok(
    e0.files[0].hash === e1.files[0].hash && e0.files[0].hash === e2.files[0].hash,
    "v3 fixture: episodes sharing a chunk report the same file hash",
  );

  // channels: sorted by name, video channel mapped to video/mp4
  const names = e0.channels.map((c) => c.name);
  const sortedNames = [...names].sort((a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)));
  ok(JSON.stringify(names) === JSON.stringify(sortedNames), "v3 fixture: channels sorted by name", JSON.stringify(names));
  const videoChannel = e0.channels.find((c) => c.name === cam);
  ok(videoChannel?.dtype === "video/mp4", "v3 fixture: video feature dtype -> video/mp4", videoChannel?.dtype);
  const stateChannel = e0.channels.find((c) => c.name === "observation.state");
  ok(
    stateChannel?.dtype === "float32" && JSON.stringify(stateChannel?.shape) === "[3]" && stateChannel?.hz === 30,
    "v3 fixture: observation.state channel dtype/shape/hz",
    JSON.stringify(stateChannel),
  );

  // readEpisodeFrames: right row counts and vector columns
  const frames0 = await readEpisodeFrames(e0, V3_DIR, ["observation.state", "action", "timestamp"]);
  ok((frames0["observation.state"] as number[]).length === 6, "v3 fixture: readEpisodeFrames row count = episode length", String((frames0["observation.state"] as number[]).length));
  ok(Array.isArray((frames0["observation.state"] as number[])[0]), "v3 fixture: observation.state rows are vectors");
  ok((frames0.timestamp as Float64Array).length === 6, "v3 fixture: scalar column returned as typed array");

  const frames2 = await readEpisodeFrames(e2, V3_DIR, ["action"]);
  ok((frames2.action as number[]).length === 7, "v3 fixture: episode 2 frame count = 7", String((frames2.action as number[]).length));
}

// =========================================================================
// v2.1-style per_episode fixture
// =========================================================================
{
  const { info, episodes } = await readDataset(V2_DIR);
  ok((info as any).codebase_version === "v2.1", "v2 fixture: codebase_version v2.1");
  ok(episodes.length === 1, "v2 fixture: 1 episode", String(episodes.length));

  const [e0] = episodes;
  ok(e0.layout === "per_episode", "v2 fixture: layout per_episode");
  ok(e0.range === null, "v2 fixture: range is null for per_episode layout");
  ok(e0.frames === 5, "v2 fixture: frame count 5", String(e0.frames));
  ok(e0.instruction === "fold the towel", "v2 fixture: instruction from meta/episodes.jsonl tasks");
  ok(e0.success === true, "v2 fixture: success from the alternate 'success' column name (not 'next.success')");
  ok(
    e0.files.length === 2 && e0.files[0].path.startsWith("data/") && e0.files[1].path.startsWith("videos/"),
    "v2 fixture: files = per-episode data file + per-episode video file",
    JSON.stringify(e0.files.map((f) => f.path)),
  );

  const frames = await readEpisodeFrames(e0, V2_DIR, ["observation.state"]);
  ok((frames["observation.state"] as number[]).length === 5, "v2 fixture: readEpisodeFrames row count = 5");
}

// =========================================================================
// Missing referenced file -> error for that episode only
// =========================================================================
{
  const dir = mkdtempSync(join(tmpdir(), "thenar-lerobot-missing-"));
  try {
    buildTinyPerEpisodeDataset(dir, [
      { episodeIndex: 0, length: 3 },
      { episodeIndex: 1, length: 4 },
    ]);
    // Remove episode 1's data file only -- episode 0 must still read fine.
    rmSync(join(dir, "data", "chunk-000", "episode_000001.parquet"));

    const originalError = console.error;
    const logged: string[] = [];
    console.error = (...args: unknown[]) => { logged.push(args.map(String).join(" ")); };
    let episodes: EpisodeRef[];
    try {
      ({ episodes } = await readDataset(dir));
    } finally {
      console.error = originalError;
    }

    ok(episodes.length === 1, "missing file: readDataset does not throw, returns the surviving episode only", String(episodes.length));
    ok(episodes[0]?.episodeIndex === 0, "missing file: surviving episode is the one whose file exists");
    ok(logged.some((l) => l.includes("episode 1")), "missing file: a per-episode error is logged for the broken episode", logged.join(" | "));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// =========================================================================
// Directory traversal rejected
// =========================================================================
{
  const dir = mkdtempSync(join(tmpdir(), "thenar-lerobot-traversal-"));
  try {
    buildTinyPerEpisodeDataset(dir, [{ episodeIndex: 0, length: 2 }]);
    // Overwrite info.json with a malicious data_path template that would
    // resolve outside the dataset directory.
    const infoPath = join(dir, "meta", "info.json");
    const info = JSON.parse(readFileSync(infoPath, "utf8"));
    info.data_path = "../../../../etc/{episode_index}.parquet";
    writeFileSync(infoPath, JSON.stringify(info));

    const originalError = console.error;
    const logged: string[] = [];
    console.error = (...args: unknown[]) => { logged.push(args.map(String).join(" ")); };
    let episodes: EpisodeRef[];
    try {
      ({ episodes } = await readDataset(dir));
    } finally {
      console.error = originalError;
    }

    ok(episodes.length === 0, "traversal: malicious template yields zero episodes (rejected, not followed)", String(episodes.length));
    ok(logged.some((l) => l.includes("..")), "traversal: assertPath's '..' rejection is surfaced in the per-episode error", logged.join(" | "));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// -------------------------------------------------------------------------

function buildTinyPerEpisodeDataset(dir: string, episodes: { episodeIndex: number; length: number }[]): void {
  const fps = 30;
  mkdirSync(join(dir, "meta"), { recursive: true });
  writeFileSync(
    join(dir, "meta", "info.json"),
    JSON.stringify({
      codebase_version: "v2.1",
      robot_type: "test_arm",
      fps,
      data_path: "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet",
      video_path: "videos/{video_key}/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.mp4",
      features: {
        "observation.state": { dtype: "float32", shape: [2], names: null },
        "observation.images.front": { dtype: "video", shape: [8, 8, 3], names: ["height", "width", "channel"] },
      },
    }),
  );
  writeFileSync(
    join(dir, "meta", "episodes.jsonl"),
    episodes.map((e) => JSON.stringify({ episode_index: e.episodeIndex, length: e.length, tasks: ["test task"] })).join("\n") + "\n",
  );

  for (const e of episodes) {
    const dataDir = join(dir, "data", "chunk-000");
    mkdirSync(dataDir, { recursive: true });
    const stateCol = Array.from({ length: e.length }, (_, i) => [i, i + 1]);
    parquetWriteFile({
      filename: join(dataDir, `episode_${String(e.episodeIndex).padStart(6, "0")}.parquet`),
      schema: [
        { name: "root", num_children: 2 },
        { name: "episode_index", type: "INT32", repetition_type: "REQUIRED" },
        { name: "observation.state", repetition_type: "OPTIONAL", converted_type: "LIST", num_children: 1 },
        { name: "list", repetition_type: "REPEATED", num_children: 1 },
        { name: "element", type: "FLOAT", repetition_type: "REQUIRED" },
      ],
      columnData: [
        { name: "episode_index", data: Array.from({ length: e.length }, () => e.episodeIndex) },
        { name: "observation.state", data: stateCol },
      ],
    });

    const videoDir = join(dir, "videos", "observation.images.front", "chunk-000");
    mkdirSync(videoDir, { recursive: true });
    writeFileSync(join(videoDir, `episode_${String(e.episodeIndex).padStart(6, "0")}.mp4`), Buffer.from([0, 1, 2, 3]));
  }
}

console.log(fails === 0 ? "\nlerobot.test.ts: all tests passed" : `\nlerobot.test.ts: ${fails} test(s) FAILED`);
if (fails > 0) process.exit(1);
