/** Emit Solidity test vectors from the reference implementation. */
import { keccak256, toHex, type Hex } from "viem";
import { encodeClip, commitConsent } from "../src/leaf";
import * as log from "../src/log";
import { SparseTree, ZERO } from "../src/sparse";
import { writeFileSync } from "node:fs";

const h = (s: string): Hex => keccak256(toHex(s));
const N = 11;
const leaves: Hex[] = Array.from({ length: N }, (_, i) => h(`clip-${i}`));
const rootN = log.root(leaves);

const arr = (xs: Hex[]) => `[${xs.map((x) => `bytes32(${x})`).join(", ")}]`;

/** Solidity has no zero-length array literal, so an empty proof is its own case. */
const proofFn = (name: string, xs: Hex[]) =>
  xs.length === 0
    ? `    function ${name}() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](0);
    }`
    : `    function ${name}() internal pure returns (bytes32[] memory p) {
        bytes32[${xs.length}] memory a = ${arr(xs)};
        p = new bytes32[](${xs.length});
        for (uint256 i; i < ${xs.length}; ++i) p[i] = a[i];
    }`;

const clip = {
  payloadHash: h("payload"),
  manifestHash: h("manifest"),
  consentCommitment: commitConsent(h("consent"), h("salt")),
  termsId: h("terms-v1"),
  capturedAt: 1787000000n,
  submittedAt: 1787000060n,
  durationMs: 4200,
  scopeBits: 0b1011,
  channels: 6,
};

const incIdx = 4;
const inc = log.inclusionProof(leaves, incIdx);
const M = 7;
const rootM = log.root(leaves.slice(0, M));
const cons = log.consistencyProof(leaves, M, N);

const t = new SparseTree();
const revoked = h("consent-key-revoked");
const live = h("consent-key-live");
const revValue = h("revocation-record");
t.set(revoked, revValue);
const sRoot = t.root();
const pIn = t.proof(revoked);
const pOut = t.proof(live);

const sol = `// SPDX-License-Identifier: MIT
// GENERATED by packages/protocol/test/vectors.ts — do not edit by hand.
// These are produced by the off-chain reference implementation, so a passing
// test means the Solidity and the TypeScript agree on every hash.
pragma solidity ^0.8.24;

library Vectors {
    bytes constant CLIP_PREIMAGE = hex"${encodeClip(clip).slice(2)}";
    bytes32 constant CLIP_LEAF = ${log.root([keccak256(("0x00" + encodeClip(clip).slice(2)) as Hex)])};

    uint64 constant N = ${N};
    bytes32 constant ROOT_N = ${rootN};
    uint64 constant INCLUSION_INDEX = ${incIdx};
    bytes32 constant INCLUSION_LEAF = ${leaves[incIdx]};

    uint64 constant M = ${M};
    bytes32 constant ROOT_M = ${rootM};

    bytes32 constant SPARSE_ROOT = ${sRoot};
    bytes32 constant KEY_REVOKED = ${revoked};
    bytes32 constant VALUE_REVOKED = ${revValue};
    bytes32 constant KEY_LIVE = ${live};
    uint256 constant BITMAP_IN = ${pIn.bitmap};
    uint256 constant BITMAP_OUT = ${pOut.bitmap};

${proofFn("inclusionProof", inc)}

${proofFn("consistencyProof", cons)}

${proofFn("sparseIn", pIn.siblings)}

${proofFn("sparseOut", pOut.siblings)}
}
`;
writeFileSync("packages/contracts/test/Vectors.sol", sol);
console.log(`wrote packages/contracts/test/Vectors.sol`);
console.log(`  log n=${N} root=${rootN.slice(0, 18)}…  inclusion proof ${inc.length} words`);
console.log(`  consistency ${M}->${N}: ${cons.length} words`);
console.log(`  sparse root=${sRoot.slice(0, 18)}…  in=${pIn.siblings.length} out=${pOut.siblings.length} words`);
