/**
 * Emit `apps/web/chains.js` from `.env.contracts` (T-009).
 *
 * `.env.contracts` is where the deploy scripts (`scripts/deploy-chain.sh`)
 * and `services/log/src/chains.ts` (T-007) agree addresses live; this is the
 * same file read into a browser-safe module so the pages never hard-code an
 * address. If `.env.contracts` is absent, falls back to
 * `.env.contracts.example` so a clean checkout still has *something* to
 * import (zero addresses, but real roles/rpcs/explorers) rather than a
 * missing file breaking every page's import.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const KNOWN = {
  43113: { name: "Avalanche Fuji", explorer: "https://testnet.snowtrace.io" },
  11155111: { name: "Ethereum Sepolia", explorer: "https://sepolia.etherscan.io" },
  84532: { name: "Base Sepolia", explorer: "https://sepolia.basescan.org" },
  31337: { name: "Anvil", explorer: "" },
};

function parseEnvFile(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const raw of readFileSync(path, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const i = line.indexOf("=");
    if (i === -1) continue;
    out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return out;
}

function loadChains(path) {
  const env = parseEnvFile(path);
  const ids = new Set();
  for (const key of Object.keys(env)) {
    const m = /^CHAIN_(\d+)_([A-Z_]+)$/.exec(key);
    if (m) ids.add(Number(m[1]));
  }
  const chains = [];
  for (const id of ids) {
    const role = env[`CHAIN_${id}_ROLE`];
    if (role !== "primary" && role !== "mirror") {
      throw new Error(`CHAIN_${id}_ROLE must be "primary" or "mirror" in ${path}, got ${JSON.stringify(role)}`);
    }
    const log = env[`CHAIN_${id}_LOG`];
    const rpc = env[`CHAIN_${id}_RPC`];
    if (!log) throw new Error(`CHAIN_${id}_LOG missing from ${path}`);
    if (!rpc) throw new Error(`CHAIN_${id}_RPC missing from ${path}`);
    const known = KNOWN[id] ?? {};
    chains.push({
      id,
      name: env[`CHAIN_${id}_NAME`] ?? known.name ?? `chain ${id}`,
      role,
      rpc,
      explorer: env[`CHAIN_${id}_EXPLORER`] ?? known.explorer ?? "",
      log,
      verifier: env[`CHAIN_${id}_VERIFIER`] ?? "",
      ...(env[`CHAIN_${id}_REGISTRY`] ? { registry: env[`CHAIN_${id}_REGISTRY`] } : {}),
    });
  }
  const primaries = chains.filter((c) => c.role === "primary");
  if (chains.length > 0 && primaries.length !== 1) {
    throw new Error(`${path} must declare exactly one primary chain; found ${primaries.length}`);
  }
  const mirrors = chains.filter((c) => c.role === "mirror").sort((a, b) => a.id - b.id);
  return [...primaries, ...mirrors];
}

const source = existsSync(join(root, ".env.contracts"))
  ? join(root, ".env.contracts")
  : join(root, ".env.contracts.example");

const chains = loadChains(source);

writeFileSync(join(root, "apps/web/chains.js"),
`/* chains.js — GENERATED by scripts/gen-chains.mjs from ${source === join(root, ".env.contracts") ? ".env.contracts" : ".env.contracts.example"}. Do not edit.
 *
 * The deployed GraspLog targets (D-9: one primary, one or more mirrors),
 * in the shape the pages read straight off the chain. Generated rather than
 * hand-kept so a page cannot show an address the deploy scripts never
 * produced; \`gen:chains\` in CI fails if this drifts from its source.
 */
export const CHAINS = ${JSON.stringify(chains, null, 2)};
`);

console.log(`wrote apps/web/chains.js — ${chains.length} chain(s) from ${source}`);
